import { LightningElement, api } from 'lwc';

/**
 * c-ai-chip - the compact SLDS 2 "AI generated" badge.
 *
 * Use this inline (next to body text, inside another card's chrome) when a
 * full c-agentic-card is too heavy. The chip carries the SLDS 2 signature
 * sparkle + info icon and a tooltip that explains the AI provenance.
 */
export default class AiChip extends LightningElement {
  @api tooltip = 'Generated by Agentforce';
}
