// Seed data for Data Enrichment, ported verbatim from
// `../UW Front End/public/setup/{app.js,integration-procedures.js,enrichment-definitions.js}`.
// Used to populate the persisted config on first load when these arrays are empty.

import type {
  EnrichmentConfig,
  EnrichmentDefinition,
  IntegrationProcedure,
} from '@/types/config';

export const SEED_ENRICHMENT_CONFIGS: EnrichmentConfig[] = [
  {
    id: 1,
    lob: 'Commercial Property',
    active: true,
    categories: [
      {
        id: 'property-characteristics',
        name: 'Property Characteristics',
        fields: [
          { name: 'Building Construction Type', type: 'Picklist' },
          { name: 'Year Built', type: 'Number' },
          { name: 'Total Building Square Footage', type: 'Number' },
          { name: 'Number of Stories', type: 'Number' },
          { name: 'Basement Type', type: 'Picklist' },
          { name: 'Roof Type', type: 'Picklist' },
          { name: 'Roof Covering Material', type: 'Picklist' },
          { name: 'Roof Age', type: 'Number' },
          { name: 'Roof Condition', type: 'Picklist' },
          { name: 'Overall Building Condition', type: 'Picklist' },
          { name: 'Wiring Type', type: 'Picklist' },
          { name: 'Electrical System Updated Year', type: 'Number' },
          { name: 'Plumbing Type', type: 'Picklist' },
          { name: 'Heating System Type', type: 'Picklist' },
          { name: 'HVAC Age', type: 'Number' },
          { name: 'Exterior Wall Material', type: 'Picklist' },
          { name: 'Foundation Type', type: 'Picklist' },
        ],
      },
      {
        id: 'location-cat-exposure',
        name: 'Location & CAT Exposure',
        fields: [
          { name: 'Property Address', type: 'Text' },
          { name: 'Latitude', type: 'Number' },
          { name: 'Longitude', type: 'Number' },
          { name: 'FEMA Flood Zone', type: 'Text' },
          { name: 'Flood Zone Panel Number', type: 'Text' },
          { name: 'Base Flood Elevation (BFE)', type: 'Number' },
          { name: 'Building First Floor Elevation', type: 'Number' },
          { name: 'Distance to Coast', type: 'Number' },
          { name: 'Distance to Major Water Body', type: 'Number' },
          { name: 'Earthquake Zone', type: 'Picklist' },
          { name: 'Peak Ground Acceleration (PGA)', type: 'Number' },
          { name: 'Probable Maximum Loss (PML) - EQ', type: 'Percent' },
          { name: 'Soil Liquefaction Risk', type: 'Picklist' },
          { name: 'Wildfire Hazard Severity Zone', type: 'Picklist' },
          { name: 'Wildfire Risk Score', type: 'Number' },
          { name: 'Distance to Fire Station', type: 'Number' },
          { name: 'Tornado Risk Zone', type: 'Picklist' },
          { name: 'Hurricane Wind Zone', type: 'Picklist' },
          { name: 'Hail Risk Zone', type: 'Picklist' },
          { name: 'Windstorm Deductible Required', type: 'Boolean' },
          { name: 'Aggregate Annual Loss (AAL)', type: 'Currency' },
          { name: 'Total Insured Value (TIV)', type: 'Currency' },
        ],
      },
      {
        id: 'fire-protection-response',
        name: 'Fire Protection & Response',
        fields: [
          { name: 'ISO Public Protection Class (PPC)', type: 'Number' },
          { name: 'Fire Hydrant Distance', type: 'Number' },
          { name: 'Number of Hydrants within 1000 ft', type: 'Number' },
          { name: 'Water Supply Type', type: 'Picklist' },
          { name: 'Water Supply Capacity (GPM)', type: 'Number' },
          { name: 'Fire Department Type', type: 'Picklist' },
          { name: 'Fire Station Response Time', type: 'Number' },
          { name: 'Automatic Sprinkler System', type: 'Picklist' },
          { name: 'Sprinkler System Type', type: 'Picklist' },
          { name: 'Sprinkler Coverage Percentage', type: 'Percent' },
          { name: 'Sprinkler System Install Date', type: 'Date' },
          { name: 'Sprinkler System Last Inspection', type: 'Date' },
          { name: 'Fire Alarm System', type: 'Picklist' },
          { name: 'Fire Alarm Monitoring Type', type: 'Picklist' },
          { name: 'Smoke Detection System', type: 'Boolean' },
          { name: 'Fire Extinguishers', type: 'Boolean' },
          { name: 'Fire Suppression System (Kitchen)', type: 'Picklist' },
          { name: 'Emergency Exit Lighting', type: 'Boolean' },
        ],
      },
      {
        id: 'occupancy-operations',
        name: 'Occupancy & Operations',
        fields: [
          { name: 'Primary Occupancy Type', type: 'Picklist' },
          { name: 'Specific Operations Description', type: 'Long Text Area' },
          { name: 'ISO Classification Code', type: 'Text' },
          { name: 'Percentage of Building - Office', type: 'Percent' },
          { name: 'Percentage of Building - Manufacturing', type: 'Percent' },
          { name: 'Percentage of Building - Warehouse', type: 'Percent' },
          { name: 'Combustible Loading', type: 'Picklist' },
          { name: 'Hazardous Materials Present', type: 'Boolean' },
          { name: 'Hazardous Materials Description', type: 'Long Text Area' },
          { name: 'Maximum Storage Height', type: 'Number' },
          { name: 'Hours of Operation', type: 'Text' },
          { name: 'Number of Shifts', type: 'Number' },
          { name: '24-Hour Watchman/Security', type: 'Boolean' },
          { name: 'Burglar Alarm System', type: 'Picklist' },
          { name: 'Security Camera System', type: 'Boolean' },
        ],
      },
      {
        id: 'claims-history',
        name: 'Claims History',
        fields: [
          { name: 'Number of Claims (5 years)', type: 'Number' },
          { name: 'Total Incurred Losses (5 years)', type: 'Currency' },
          { name: 'Number of Fire Claims', type: 'Number' },
          { name: 'Number of Water Damage Claims', type: 'Number' },
          { name: 'Number of Theft Claims', type: 'Number' },
          { name: 'Number of Wind/Hail Claims', type: 'Number' },
          { name: 'Largest Single Claim Amount', type: 'Currency' },
          { name: 'Most Recent Claim Date', type: 'Date' },
          { name: 'Most Recent Claim Description', type: 'Long Text Area' },
          { name: 'Claim Frequency (per $1M TIV)', type: 'Number' },
          { name: 'Claim Severity Average', type: 'Currency' },
          { name: 'Industry Average Claim Frequency', type: 'Number' },
          { name: 'Industry Average Claim Severity', type: 'Currency' },
          { name: 'Open Claims Count', type: 'Number' },
          { name: 'Subrogation Recoveries', type: 'Currency' },
        ],
      },
      {
        id: 'valuation-itv',
        name: 'Valuation & Insurance-to-Value',
        fields: [
          { name: 'Building Replacement Cost', type: 'Currency' },
          { name: 'Contents/PP&E Replacement Cost', type: 'Currency' },
          { name: 'Business Income Annual Value', type: 'Currency' },
          { name: 'Business Income Indemnity Period', type: 'Number' },
          { name: 'Extra Expense Value', type: 'Currency' },
          { name: 'Total Insured Value (TIV)', type: 'Currency' },
          { name: 'Building Insurance Amount', type: 'Currency' },
          { name: 'Contents Insurance Amount', type: 'Currency' },
          { name: 'BI/EE Insurance Amount', type: 'Currency' },
          { name: 'Insurance-to-Value Ratio (Building)', type: 'Percent' },
          { name: 'Insurance-to-Value Ratio (Total)', type: 'Percent' },
          { name: 'Coinsurance Penalty Potential', type: 'Currency' },
        ],
      },
      {
        id: 'building-code-compliance',
        name: 'Building Code & Compliance',
        fields: [
          { name: 'Building Code Year', type: 'Number' },
          { name: 'ADA Compliance Status', type: 'Picklist' },
          { name: 'Asbestos Present', type: 'Boolean' },
          { name: 'Lead Paint Present', type: 'Boolean' },
          { name: 'Underground Storage Tanks', type: 'Boolean' },
          { name: 'Radon Mitigation System', type: 'Boolean' },
          { name: 'Fire Code Compliance', type: 'Picklist' },
          { name: 'Occupancy Permit Current', type: 'Boolean' },
          { name: 'Recent Building Violations', type: 'Number' },
          { name: 'Renovations in Last 5 Years', type: 'Boolean' },
        ],
      },
    ],
  },
  {
    id: 2,
    lob: 'General Liability',
    active: true,
    categories: [
      {
        id: 'business-operations-exposure',
        name: 'Business Operations & Exposure',
        fields: [
          { name: 'Legal Business Name', type: 'Text' },
          { name: 'DBA (Doing Business As)', type: 'Text' },
          { name: 'Legal Entity Type', type: 'Picklist' },
          { name: 'Federal Tax ID (EIN)', type: 'Text' },
          { name: 'DUNS Number', type: 'Text' },
          { name: 'Years in Business', type: 'Number' },
          { name: 'Years Under Current Management', type: 'Number' },
          { name: 'Primary SIC Code', type: 'Text' },
          { name: 'Primary NAICS Code', type: 'Text' },
          { name: 'Business Description', type: 'Long Text Area' },
          { name: 'Annual Gross Revenue', type: 'Currency' },
          { name: 'Annual Payroll', type: 'Currency' },
          { name: 'Number of Full-Time Employees', type: 'Number' },
          { name: 'Number of Part-Time Employees', type: 'Number' },
          { name: 'Total Employee Count', type: 'Number' },
          { name: 'Products Manufactured', type: 'Long Text Area' },
          { name: 'Annual Product Sales', type: 'Currency' },
          { name: 'Services Provided', type: 'Long Text Area' },
          { name: 'Annual Service Revenue', type: 'Currency' },
          { name: 'Installation Services Provided', type: 'Boolean' },
          { name: 'Percentage Work On-Site', type: 'Percent' },
          { name: 'Percentage Work Off-Site', type: 'Percent' },
          { name: 'Subcontractors Used', type: 'Boolean' },
          { name: 'Annual Subcontractor Costs', type: 'Currency' },
        ],
      },
      {
        id: 'gl-claims-history',
        name: 'GL Claims History',
        fields: [
          { name: 'Number of GL Claims (5 years)', type: 'Number' },
          { name: 'Total GL Incurred (5 years)', type: 'Currency' },
          { name: 'Number of Bodily Injury Claims', type: 'Number' },
          { name: 'Number of Property Damage Claims', type: 'Number' },
          { name: 'Number of Products Liability Claims', type: 'Number' },
          { name: 'Number of Completed Ops Claims', type: 'Number' },
          { name: 'Largest GL Claim Amount', type: 'Currency' },
          { name: 'Most Recent GL Claim Date', type: 'Date' },
          { name: 'Most Recent GL Claim Description', type: 'Long Text Area' },
          { name: 'GL Claim Frequency Rate', type: 'Number' },
          { name: 'Industry Average GL Frequency', type: 'Number' },
          { name: 'Open GL Claims Count', type: 'Number' },
        ],
      },
      {
        id: 'safety-programs-osha',
        name: 'Safety Programs & OSHA',
        fields: [
          { name: 'Written Safety Program', type: 'Boolean' },
          { name: 'Safety Director/Officer', type: 'Boolean' },
          { name: 'Regular Safety Training', type: 'Picklist' },
          { name: 'New Employee Safety Orientation', type: 'Boolean' },
          { name: 'PPE Program', type: 'Boolean' },
          { name: 'Machine Guarding Program', type: 'Boolean' },
          { name: 'Lockout/Tagout Program', type: 'Boolean' },
          { name: 'Hazard Communication Program', type: 'Boolean' },
          { name: 'Emergency Action Plan', type: 'Boolean' },
          { name: 'OSHA 300 Log Maintained', type: 'Boolean' },
          { name: 'OSHA Inspections (5 years)', type: 'Number' },
          { name: 'OSHA Violations (5 years)', type: 'Number' },
          { name: 'OSHA Serious Violations', type: 'Number' },
          { name: 'OSHA Violations Abated', type: 'Boolean' },
          { name: 'DART Rate (Days Away/Restricted)', type: 'Number' },
          { name: 'TRIR (Total Recordable Incident Rate)', type: 'Number' },
        ],
      },
      {
        id: 'workers-comp-experience',
        name: 'Workers Compensation Experience',
        fields: [
          { name: 'Experience Modification Rate (EMR)', type: 'Number' },
          { name: 'EMR Effective Date', type: 'Date' },
          { name: 'Prior Year EMR', type: 'Number' },
          { name: 'EMR Trend', type: 'Picklist' },
          { name: 'Number of WC Claims (5 years)', type: 'Number' },
          { name: 'Total WC Incurred (5 years)', type: 'Currency' },
          { name: 'Number of Lost Time Claims', type: 'Number' },
          { name: 'Number of Medical Only Claims', type: 'Number' },
          { name: 'Largest WC Claim Amount', type: 'Currency' },
          { name: 'Return to Work Program', type: 'Boolean' },
          { name: 'WC Claim Frequency Rate', type: 'Number' },
          { name: 'Industry Average EMR', type: 'Number' },
          { name: 'Open WC Claims Count', type: 'Number' },
          { name: 'WC Coverage Current', type: 'Boolean' },
        ],
      },
      {
        id: 'financial-stability-credit',
        name: 'Financial Stability & Credit',
        fields: [
          { name: 'D&B Credit Rating', type: 'Text' },
          { name: 'D&B Credit Rating Score', type: 'Number' },
          { name: 'D&B Credit Risk Level', type: 'Picklist' },
          { name: 'D&B PAYDEX Score', type: 'Number' },
          { name: 'D&B Financial Stress Score', type: 'Number' },
          { name: 'D&B Failure Score', type: 'Number' },
          { name: 'D&B Delinquency Score', type: 'Percent' },
          { name: 'Annual Revenue (D&B)', type: 'Currency' },
          { name: 'Number of Employees (D&B)', type: 'Number' },
          { name: 'Years in Business (D&B)', type: 'Number' },
          { name: 'Out of Business Score', type: 'Percent' },
          { name: 'Public Records - Liens', type: 'Number' },
          { name: 'Public Records - Judgments', type: 'Number' },
          { name: 'Public Records - Bankruptcies', type: 'Number' },
          { name: 'Trade Payment Experiences', type: 'Number' },
          { name: 'Average Days to Pay', type: 'Number' },
          { name: 'Revenue Growth Rate (3 yr)', type: 'Percent' },
          { name: 'Financial Statement Available', type: 'Boolean' },
        ],
      },
      {
        id: 'products-liability-exposure',
        name: 'Products Liability Exposure',
        fields: [
          { name: 'Products Sold Annually (Units)', type: 'Number' },
          { name: 'Products Sold - Dollar Volume', type: 'Currency' },
          { name: 'Product Categories', type: 'Picklist' },
          { name: 'Product Testing Program', type: 'Boolean' },
          { name: 'Product Recalls (5 years)', type: 'Number' },
          { name: 'Product Warranty Period', type: 'Text' },
          { name: 'Product Instructions/Warnings', type: 'Boolean' },
          { name: 'FDA Regulated Products', type: 'Boolean' },
          { name: 'UL Listed/Certified Products', type: 'Boolean' },
          { name: 'Product Shelf Life', type: 'Text' },
          { name: 'Export Sales Percentage', type: 'Percent' },
          { name: 'Product Liability Limit Purchased', type: 'Currency' },
        ],
      },
      {
        id: 'contractual-operations-risk',
        name: 'Contractual & Operations Risk',
        fields: [
          { name: 'Percentage Work via Written Contract', type: 'Percent' },
          { name: 'Hold Harmless Agreements Signed', type: 'Boolean' },
          { name: 'Additional Insured Required by Contract', type: 'Boolean' },
          { name: 'Waiver of Subrogation Required', type: 'Boolean' },
          { name: 'Maximum Contract Size', type: 'Currency' },
          { name: 'Government Contracts', type: 'Boolean' },
          { name: 'Professional Services Provided', type: 'Boolean' },
          { name: 'Pollution Exposure', type: 'Picklist' },
          { name: 'Liquor Liability Exposure', type: 'Boolean' },
          { name: 'Employee Benefits Liability', type: 'Boolean' },
        ],
      },
    ],
  },
];

export const SEED_INTEGRATION_PROCEDURES: IntegrationProcedure[] = [
  {
    id: 1,
    name: 'Verisk360_GetPropertyValuation',
    procName: 'Verisk360',
    versionLabel: 'GetPropertyValuation',
    description: 'Pull 360Value building replacement-cost report and building characteristics.',
    lob: 'Commercial Property',
    provider: 'Verisk 360',
    active: true,
    lastModified: '2026-06-09T10:32:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'setRequestPayload', type: 'Set Values', description: 'Map ACORD 140 location + structural fields into Verisk request.' },
      { id: 2, name: 'callVerisk360Api', type: 'HTTP Action', description: 'POST /v1/360value/properties — fetch valuation + characteristics.' },
      { id: 3, name: 'cacheValuation', type: 'Cache Block', description: 'Cache by latitude/longitude for 24h.' },
      { id: 4, name: 'extractFields', type: 'Set Values', description: 'Map response to Property Characteristics + Valuation enrichment fields.' },
      { id: 5, name: 'returnEnrichment', type: 'Response Action', description: 'Return building replacement cost, construction type, year built, square footage.' },
    ],
  },
  {
    id: 2,
    name: 'CoreLogic_GetCATExposure',
    procName: 'CoreLogic',
    versionLabel: 'GetCATExposure',
    description: 'Geocode the address and pull all CAT-exposure data (flood, EQ, wildfire, hurricane, hail).',
    lob: 'Commercial Property',
    provider: 'CoreLogic',
    active: true,
    lastModified: '2026-06-09T11:10:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'geocodeAddress', type: 'HTTP Action', description: 'POST /geocode — resolve street address to lat/lng.' },
      { id: 2, name: 'lookupFloodZone', type: 'HTTP Action', description: 'GET /risk/flood — FEMA flood zone, BFE, panel id.' },
      { id: 3, name: 'lookupEarthquakeRisk', type: 'HTTP Action', description: 'GET /risk/earthquake — PGA, soil liquefaction, PML.' },
      { id: 4, name: 'lookupWildfireRisk', type: 'HTTP Action', description: 'GET /risk/wildfire — hazard severity zone + wildfire risk score.' },
      { id: 5, name: 'lookupHurricaneRisk', type: 'HTTP Action', description: 'GET /risk/hurricane — wind zone, distance to coast.' },
      { id: 6, name: 'aggregateExposureRisks', type: 'Set Values', description: 'Combine all CAT outputs into a single response object.' },
      { id: 7, name: 'returnEnrichment', type: 'Response Action', description: 'Return Location & CAT Exposure fields.' },
    ],
  },
  {
    id: 3,
    name: 'ISO_GetPublicProtectionClass',
    procName: 'ISO',
    versionLabel: 'GetPublicProtectionClass',
    description: 'Fetch ISO PPC, fire-department type, hydrant distance, water supply data.',
    lob: 'Commercial Property',
    provider: 'ISO Public Protection',
    active: true,
    lastModified: '2026-06-09T09:50:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'setRequestPayload', type: 'Set Values', description: 'Build ISO request from address + lat/lng.' },
      { id: 2, name: 'callIsoPpcApi', type: 'HTTP Action', description: 'GET /ppc/lookup — ISO PPC class + fire protection.' },
      { id: 3, name: 'cachePpc', type: 'Cache Block', description: 'Cache by ZIP + protection district for 30 days.' },
      { id: 4, name: 'extractProtectionFields', type: 'Set Values', description: 'Map PPC, hydrant distance, water supply, FD type, response time.' },
      { id: 5, name: 'returnEnrichment', type: 'Response Action', description: 'Return Fire Protection & Response fields.' },
    ],
  },
  {
    id: 4,
    name: 'LexisNexis_GetClaimsHistory',
    procName: 'LexisNexis',
    versionLabel: 'GetClaimsHistory',
    description: 'Pull 5-year commercial CLUE history and aggregate by peril.',
    lob: 'Commercial Property',
    provider: 'LexisNexis CLUE Commercial',
    active: true,
    lastModified: '2026-06-09T08:21:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'authenticate', type: 'HTTP Action', description: 'Exchange API key for short-lived bearer token.' },
      { id: 2, name: 'requestClueReport', type: 'HTTP Action', description: 'POST /clue/commercial/v2/lookup — request 5y claims history.' },
      { id: 3, name: 'parseClaims', type: 'Loop Block', description: 'Iterate claims; bucket by peril (fire, water, theft, wind/hail).' },
      { id: 4, name: 'computeAggregates', type: 'Set Values', description: 'Total incurred, claim frequency, severity, largest claim.' },
      { id: 5, name: 'fetchIndustryBenchmarks', type: 'Remote Action', description: 'Look up ISO industry-average frequency + severity.' },
      { id: 6, name: 'returnEnrichment', type: 'Response Action', description: 'Return Claims History fields.' },
    ],
  },
  {
    id: 5,
    name: 'DnB_GetBusinessProfile',
    procName: 'DnB',
    versionLabel: 'GetBusinessProfile',
    description: 'Pull D&B business profile, credit scores, public records.',
    lob: 'General Liability',
    provider: 'D&B (Dun & Bradstreet)',
    active: true,
    lastModified: '2026-06-09T07:45:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'matchByDuns', type: 'Conditional Block', description: 'If DUNS provided, lookup by DUNS; else match by legal name + address.' },
      { id: 2, name: 'fetchProfile', type: 'HTTP Action', description: 'GET /v1/data/duns/{duns} — base profile + entity info.' },
      { id: 3, name: 'fetchCreditScores', type: 'HTTP Action', description: 'GET /v1/data/duns/{duns}/credit — PAYDEX, failure score, financial stress.' },
      { id: 4, name: 'fetchPublicRecords', type: 'HTTP Action', description: 'GET /v1/data/duns/{duns}/public-records — liens, judgments, bankruptcies.' },
      { id: 5, name: 'mergeFields', type: 'Set Values', description: 'Combine into Business Operations + Financial Stability output.' },
      { id: 6, name: 'returnEnrichment', type: 'Response Action', description: 'Return Business Operations + Financial Stability fields.' },
    ],
  },
  {
    id: 6,
    name: 'OSHA_GetSafetyHistory',
    procName: 'OSHA',
    versionLabel: 'GetSafetyHistory',
    description: 'Look up OSHA inspections, violations, abatement status by establishment.',
    lob: 'General Liability',
    provider: 'OSHA Enforcement API',
    active: true,
    lastModified: '2026-06-09T07:15:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'matchEstablishment', type: 'HTTP Action', description: 'GET /v1/establishments?ein=… — find establishment ids.' },
      { id: 2, name: 'fetchInspections', type: 'HTTP Action', description: 'GET /v1/inspections?establishmentId=… (5-year window).' },
      { id: 3, name: 'fetchViolations', type: 'Loop Block', description: 'For each inspection, fetch citations + abatement status.' },
      { id: 4, name: 'aggregateOshaMetrics', type: 'Set Values', description: 'Inspection count, violation count, serious violations, abatement %.' },
      { id: 5, name: 'returnEnrichment', type: 'Response Action', description: 'Return Safety Programs & OSHA fields.' },
    ],
  },
  {
    id: 7,
    name: 'NCCI_GetWorkersCompEMR',
    procName: 'NCCI',
    versionLabel: 'GetWorkersCompEMR',
    description: 'Fetch experience modification factor and recent WC claim history.',
    lob: 'General Liability',
    provider: 'NCCI',
    active: true,
    lastModified: '2026-06-09T06:55:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'lookupRiskId', type: 'HTTP Action', description: 'GET /risk-id/lookup?ein=… — resolve NCCI risk id.' },
      { id: 2, name: 'fetchEmr', type: 'HTTP Action', description: 'GET /experience-mod/{riskId} — current + prior EMR.' },
      { id: 3, name: 'computeTrend', type: 'Set Values', description: 'Compare current vs prior EMR → Improving / Stable / Declining.' },
      { id: 4, name: 'fetchWcClaims', type: 'Remote Action', description: 'Pull WC claims from current carrier.' },
      { id: 5, name: 'returnEnrichment', type: 'Response Action', description: 'Return Workers Compensation Experience fields.' },
    ],
  },
  {
    id: 8,
    name: 'Enrichment_RunAllForSubmission',
    procName: 'Enrichment',
    versionLabel: 'RunAllForSubmission',
    description: 'Orchestrator — fans out to all relevant provider IPs based on submission LOB and aggregates results.',
    lob: 'All',
    provider: 'Orchestrator',
    active: true,
    lastModified: '2026-06-10T14:00:00Z',
    invocationMode: 'Standalone',
    steps: [
      { id: 1, name: 'detectLineOfBusiness', type: 'Set Values', description: 'Inspect submission to determine which IPs to invoke.' },
      { id: 2, name: 'isCommercialProperty', type: 'Conditional Block', description: 'If submission contains Property line, run Verisk + CoreLogic + ISO + LexisNexis.' },
      { id: 3, name: 'isGeneralLiability', type: 'Conditional Block', description: 'If submission contains GL line, run D&B + OSHA + NCCI.' },
      { id: 4, name: 'callPropertyEnrichments', type: 'Loop Block', description: 'Fan-out to property IPs in parallel and collect results.' },
      { id: 5, name: 'callGeneralLiabilityEnrichments', type: 'Loop Block', description: 'Fan-out to GL IPs in parallel and collect results.' },
      { id: 6, name: 'mergeAndDedupe', type: 'Set Values', description: 'Combine outputs; resolve overlaps using source priority.' },
      { id: 7, name: 'persistEnrichmentRecord', type: 'Remote Action', description: 'Persist combined enrichment record on the submission.' },
      { id: 8, name: 'returnSummary', type: 'Response Action', description: 'Return enrichment summary + any provider errors.' },
    ],
  },
];

export const SEED_ENRICHMENT_DEFINITIONS: EnrichmentDefinition[] = [
  {
    id: 1,
    name: 'Property Characteristics — Verisk 360',
    lob: 'Commercial Property',
    categoryId: 'property-characteristics',
    categoryName: 'Property Characteristics',
    integrationProcedureName: 'Verisk360_GetPropertyValuation',
    active: true,
    lastModified: '2026-06-09T10:32:00Z',
  },
  {
    id: 2,
    name: 'Location & CAT Exposure — CoreLogic',
    lob: 'Commercial Property',
    categoryId: 'location-cat-exposure',
    categoryName: 'Location & CAT Exposure',
    integrationProcedureName: 'CoreLogic_GetCATExposure',
    active: true,
    lastModified: '2026-06-09T11:10:00Z',
  },
  {
    id: 3,
    name: 'Fire Protection — ISO PPC',
    lob: 'Commercial Property',
    categoryId: 'fire-protection-response',
    categoryName: 'Fire Protection & Response',
    integrationProcedureName: 'ISO_GetPublicProtectionClass',
    active: true,
    lastModified: '2026-06-09T09:50:00Z',
  },
  {
    id: 4,
    name: 'Claims History — LexisNexis CLUE',
    lob: 'Commercial Property',
    categoryId: 'claims-history',
    categoryName: 'Claims History',
    integrationProcedureName: 'LexisNexis_GetClaimsHistory',
    active: true,
    lastModified: '2026-06-09T08:21:00Z',
  },
];
